name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      debug-build:
        description: 'Trigger debug build'
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-artifacts
        path: app/build/outputs/**

    # Add a step for debug build if manually triggered
    - name: Debug Build
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.debug-build
      run: ./gradlew buildDebug
        
